### ISSUE TITLE
lactate value doesn´t change between athletes

### ISSUE THREAD

**Issue by IOSUT** [cran/lactater#1]
despite using different data of test the value of lactate of different methods still appearing as the same.... something it´s worng? thanks.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by IOSUT** [comment]
Thanks and sorry
